schema = 1

[mod]
  [mod."github.com/bwmarrin/discordgo"]
    version = "v0.23.2"
    hash = "sha256-yb+pC0SfqTZEgkYcBbpIhEjgAjr2pf9slve8mWtn47s="
  [mod."github.com/eaburns/peggy"]
    version = "v1.0.0"
    hash = "sha256-L12jxdzIUNojdi2zhJbharGckTrsogifdTxsQuflLkQ="
  [mod."github.com/eaburns/pretty"]
    version = "v1.0.0"
    hash = "sha256-FpEhv4LBEs4gWnPWuodLfI09ePVsFpLG6C+aWVZeuDU="
  [mod."github.com/eaburns/toaq"]
    version = "v0.0.0-20210614121731-80ccb209650b"
    hash = "sha256-OTfouK200vqAwXE5mz7Yxec5qhjkxnGOU+xr1IAkdUc="
  [mod."github.com/google/go-cmp"]
    version = "v0.3.1"
    hash = "sha256-oUPl5ojctSzSgOSdWB3HeQ5NOcTFtXly7HLSC2IiXLE="
  [mod."github.com/gorilla/websocket"]
    version = "v1.4.1"
    hash = "sha256-+yo/0+zSqf2/dPZyp/9so21r7cfMx1yhxmmOzy2wwQ4="
  [mod."github.com/velour/chat"]
    version = "v0.0.0-20180713122344-fd1d1606cb89"
    hash = "sha256-pr0+BC/SNcajsJm57GjMDoc59GRX+yHD+9FmaGQLsqs="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20181030102418-4d3f4d9ffa16"
    hash = "sha256-SIDwR1LoOc67PhvZFazkZSph9rUvuKy1MEFhbqp8emk="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."golang.org/x/tools"]
    version = "v0.0.0-20180917221912-90fa682c2a6e"
    hash = "sha256-NPoE7uVvwjV2PRIxI3DpegOZc8IuUs4XUJuH3ubKHJg="
