schema = 3

[mod]
  [mod."github.com/JohannesKaufmann/html-to-markdown"]
    version = "v1.3.5"
    hash = "sha256-4iVI80RTN8ZysUkCYa9vEq2M2kEMCG6OCwKG8Og/Xmg="
  [mod."github.com/PuerkitoBio/goquery"]
    version = "v1.5.1"
    hash = "sha256-GqxIdhuN1L3enT8pNlWm+rmkdN5uMfF8TfpxhAHhEDQ="
  [mod."github.com/andybalholm/cascadia"]
    version = "v1.1.0"
    hash = "sha256-mL40/Q9iXBzzMHwMomqTOpp9rnI/MRsufb5cIU1MMPg="
  [mod."github.com/bwmarrin/discordgo"]
    version = "v0.25.0"
    hash = "sha256-GKaTov5xrWZwdOyfGAtzJ84+Fbmd5bBHli/nMazTkjs="
  [mod."github.com/eaburns/peggy"]
    version = "v1.0.0"
    hash = "sha256-L12jxdzIUNojdi2zhJbharGckTrsogifdTxsQuflLkQ="
  [mod."github.com/eaburns/toaq"]
    version = "v0.0.0-20210614121731-80ccb209650b"
    hash = "sha256-OTfouK200vqAwXE5mz7Yxec5qhjkxnGOU+xr1IAkdUc="
  [mod."github.com/gorilla/websocket"]
    version = "v1.4.2"
    hash = "sha256-GhBLM/XTm2lFCyDvJbnCLAI2OyYXQV6W+jRPOQ1PdVY="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20210421170649-83a5a9bb288b"
    hash = "sha256-/yDFKCgawG9Othmh5y0O3Vx79JH2t4N7ecp1Nr+Li3o="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20210226172049-e18ecbb05110"
    hash = "sha256-4u7XpPV+Ersntau6zUiLuNsZQZCIIZs3RouHYl/I02o="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20201119102817-f84b799fce68"
    hash = "sha256-EH5wVq9wsiELXlF4f/22eOyOtHrU3XZfTxyXHvCfeVM="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
